# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'gem-browse'
gem 'neovim'
gem 'puppet-lint'
gem 'sorbet', :group => :development
gem 'sorbet-runtime'
