#!/usr/bin/env bash

set -e

# =============================================================================
# Require DOTFILES
# =============================================================================

if [[ -z "$DOTFILES" ]]; then
  echo ".dotfiles repo is not set up"
  exit 1
fi
. "${DOTFILES}/lib/pretty.bash"

# =============================================================================
# Main
# =============================================================================

__install() {
  # @TODO check for chruby

  __dko_status "Cleaning up gems with broken names"
  gem uninstall scss-lint

  # loop through default-gems file and install each one
  __dko_status "Installing default gems"
  while read -r gemname; do
    gem install "$gemname"
  done < "${DOTFILES}/ruby/default-gems"
}

__install

