#!/usr/bin/env bash

# =============================================================================
# Require DOTFILES
# =============================================================================

if [[ -z "$DOTFILES" ]]; then
  cd -- "$(dirname "$0")/.." || exit 1
  DOTFILES="$PWD"
fi
. "${DOTFILES}/lib/pretty.bash"

# =============================================================================
# Main
# =============================================================================

__install() {
  { which ruby | grep -q rubies; } || {
    __dko_err  "Not using ruby in userspace"
    exit 1
  }

  __dko_status "Cleaning up gems with broken names"
  gem uninstall scss-lint

  # loop through default-gems file and install each one
  __dko_status "Installing default gems"
  while read -r gemname; do
    gem install "$gemname"
  done < "${DOTFILES}/ruby/default-gems"
}

__install
