#!/usr/bin/env bash

# Shell aliases
# Not run by loader
# Sourced by both .zshrc and .bashrc, so keep it bash compatible

alias testnotification="notify-send 'Hello world!' 'This is an example notification.' --icon=dialog-information"

# paths and dirs
alias ..="cd .."
alias ....="cd ../.."
alias cd..="cd .."
alias dirs="dirs -v"                  # default to vert, use -l for list
alias tree="tree -C"

# ls aliases
alias l="ls   --almost-all --classify -l"
alias la="ls  --almost-all --classify"
alias ll="ls  --almost-all --classify -1 -l"

# bin
alias b="brew"
alias bun="bundle"
alias be="bundle exec"
alias c="composer"
alias e="vopen"
alias f="find"
alias g="git"
alias g-="git co -"
alias gb="git browse"
alias n="npm"
alias pac="pacaur"
alias p="php"
alias py="python"
alias py2="python2"
alias py3="python3"
alias u="update"
alias v="vagrant"
alias vag="vagrant"
alias vb="VBoxManage"
alias vbm="VBoxManage"
alias startx="startx > ~/.dotfiles/logs/startx.log 2>&1"

# function-type aliases
alias publicip="curl icanhazip.com"
# really clear the scrollback
alias tpr="tput reset"
alias mine='sudo chown -R $USER'
alias xkbreset="setxkbmap -layout us && xmodmap ~/.Xmodmap"
alias today="date +%Y-%m-%d"

# default flags for programs
alias df="df -h"
# Always enable colored `grep` output
alias grep="grep --color=auto"
alias ln="ln -v"
# better than sudo su -- use current shell instead
alias rsync='rsync --human-readable --partial --progress'
alias wget="wget --no-check-certificate"

# sudo ops
alias root="sudo -s"
alias se="sudo -e"

# quick edits
alias ealiases='e $DOTFILES/shell/aliases'
alias efunctions='e $DOTFILES/shell/functions'
alias epaths='e $BASH_DOTFILES/paths.sh'
alias ebashrc='e $BASH_DOTFILES/bashrc.sh'
alias elbashrc='e $HOME/.bashrc.local'
alias ehosts="sudo vim /etc/hosts"
alias evg="e ~/.vim/gvimrc"
alias evm="e ~/.vim/plugin/mappings.vim"
alias evp="e ~/.vim/neobundle.vim"
alias evr="e ~/.vim/vimrc"

# os specific
case "$OSTYPE" in
  darwin*)
    alias ls="ls -G -p"

    # clear xattrs
    alias xc="xattr -c *"

    # Audio control - http://xkcd.com/530/
    alias stfu="osascript -e 'set volume output muted true'"
    alias pumpitup="osascript -e 'set volume 7'"
    ;;
  linux*)

    [ "$DOTFILES_DISTRO" != "busybox" ] && {
      alias ls="ls --color=auto --time-style=\"+%Y%m%d\""
    }

    alias open="o"

    [ "$DOTFILES_DISTRO" = "archlinux" ] && {
      alias y="yaourt"
      alias pac="sudo pacman"
      alias thu="thunar"
    }

    [ "$DOTFILES_DISTRO" = "debian" ] && {
      alias a="sudo aptitude -F \"%p %d %v\""
    }

    ;;
esac

# vim: syntax=sh :
