#!/bin/bash
# 1.  don't bother checking for path existence since system will skip
#     automatically
# 2.  don't use BREW_PREFIX since we always want /usr/local/ paths

# Bottom supercedes top

# local binaries
PATH="/usr/local/sbin:$PATH"
PATH="/usr/local/bin:$PATH"

# package managers -------------------------------------------------------------

# composer
PATH="$HOME/.composer/vendor/bin:$PATH"

# npm
# brew npm
PATH="$BREW_PREFIX/share/npm/bin:$PATH"
# home packages
[ -d "$NPM_PACKAGES" ] && {
  PATH="$NPM_PACKAGES/bin:$PATH"
  unset MANPATH
  export MANPATH="$NPM_PACKAGES/share/man:$(manpath)"
}

# go
PATH="$GOPATH/bin:$PATH"

# local ------------------------------------------------------------------------
PATH="$DOTFILES/bin:$PATH"
PATH="$HOME/bin:$PATH"
export PATH

# vim: set ft=sh :
