#!/usr/bin/env bash

# Shell variables
# Run from loader
#
# Some things from env are here since OSX doesn't start new env for each term
# and we may need to reset the values

export LC_ALL="en_US.UTF-8"
export LANG="en_US"

# dotfile paths ----------------------------------------------------------------
export DOTFILES="$HOME/.dotfiles"
export BASH_DOTFILES="$DOTFILES/bash"
export ZDOTDIR="$DOTFILES/zsh"

# LP_OS detection, default to Linux --------------------------------------------
# https://github.com/nojhan/liquidprompt/blob/master/liquidprompt
case $(uname) in
    FreeBSD)   export DOTFILES_OS="FreeBSD" ;;
    DragonFly) export DOTFILES_OS="FreeBSD" ;;
    OpenBSD)   export DOTFILES_OS="OpenBSD" ;;
    Darwin)    export DOTFILES_OS="Darwin"  ;;
    SunOS)     export DOTFILES_OS="SunOS"   ;;
    *)         export DOTFILES_OS="Linux"   ;;
esac
[[ $DOTFILES_OS = "Darwin" ]] && {
  case "$(sw_vers -productVersion)" in
    10.7*) export DOTFILES_DISTRO="lion"          ;;
    10.8*) export DOTFILES_DISTRO="mountainlion"  ;;
    10.9*) export DOTFILES_DISTRO="mavericks"     ;;
  esac
}
[[ $DOTFILES_OS = "Linux" ]] && {
  [[ -f "/etc/debian_version" ]] && export DOTFILES_DISTRO="debian"
  [[ -f "/etc/arch-release" ]]   && export DOTFILES_DISTRO="archlinux"
}

# Shell settings ---------------------------------------------------------------
# xdg-user-dirs
[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/user-dirs.dirs" ] && source "${XDG_CONFIG_HOME:-$HOME/.config}/user-dirs.dirs"

export INPUTRC="$DOTFILES/shell/.inputrc"

export SAVEHIST=1000
export HISTSIZE=1000
export HISTFILESIZE="$HISTSIZE";
export HISTCONTROL=ignoredups;
export HISTIGNORE="ls:cd:cd -:pwd:exit:date:* --help";

# program settings -------------------------------------------------------------
# for rsync and cvs
export ACKRC="$DOTFILES/ack/.ackrc"
export CVSIGNORE="$DOTFILES/git/.gitignore"
export EDITOR="e --nofork"
export VISUAL="e --nofork"
# Don't clear the screen after quitting a manual page
export SCREENRC="$DOTFILES/screen/.screenrc"

# pager ----------------------------------------
# less
# -F quit if one screen (default)
# -N line numbers
# -R raw control chars (default)
# -X don't clear screen on quit
# -e LESS option to quit at EOF
export LESS="-eFRX"
export LESSHST="$DOTFILES/less/.lesshst"

export PAGER="less"
export MANPAGER="$PAGER"
export GIT_PAGER="$PAGER"

# others ----------------------------------------

# apache
[[ -f /etc/apache2/envvars ]] && source /etc/apache2/envvars
has_program "apachectl" && {
  if apachectl -t >/dev/null 2>&1; then
    APACHE_HTTPD_ROOT="$(apachectl -V | awk '/ -D HTTPD_ROOT/ { print $2 }' | cut -d "=" -f2 | sed 's/\"//g')"
    APACHE_HTTPD_CONF="$(apachectl -V | awk '/ -D SERVER_CONFIG_FILE/ { print $2 }' | cut -d "=" -f2 | sed 's/\"//g')"
    export APACHE_HTTPD_ROOT
    export APACHE_HTTPD_CONF
  fi
}

# boot2docker
export DOCKER_HOST="tcp://localhost:4243"

# chruby
# overridden in homebrew section if has brew
export CHRUBY_PREFIX="/usr"

# go
# used in shell/paths
export GOPATH="$HOME/go"

# homebrew
has_program "brew" && {
  BREW_PREFIX="$(brew --prefix)"
  export BREW_PREFIX
  export CHRUBY_PREFIX="$BREW_PREFIX"
  export HOMEBREW_CASK_OPTS="--appdir=/Applications"

  # Ruby use brew openssl if available
  [[ -f "$BREW_PREFIX/opt/openssl" ]] && export RUBY_CONFIGURE_OPTS="--with-openssl-dir=$BREW_PREFIX/opt/openssl"
}

# node
export NVM_DIR="$HOME/.nvm"
# consider using NODE_PATH="$(npm root -g):$NODE_PATH" so nvm specific
# node_path is also checked
export NODE_PATH="/usr/local/lib/node_modules:$NODE_PATH"
export NPM_PACKAGES="$HOME/.npm-packages"

# vopen
export VOPEN_DEFAULT_COMMAND="+VimFilerCurrentDir"

# z
export _Z_CMD=j
#export _Z_DATA="$DOTFILES/z/.z"

# vim: syntax=sh :
