#!/bin/bash
export LC_ALL="en_US.UTF-8"
export LANG="en_US"

# dotfile paths ----------------------------------------------------------------
export DOTFILES="$HOME/.dotfiles"
export BASH_DOTFILES="$DOTFILES/bash"
export ZDOTDIR="$DOTFILES/zsh"

# LP_OS detection, default to Linux --------------------------------------------
# https://github.com/nojhan/liquidprompt/blob/master/liquidprompt
case $(uname) in
    FreeBSD)   export DOTFILES_OS="FreeBSD" ;;
    DragonFly) export DOTFILES_OS="FreeBSD" ;;
    OpenBSD)   export DOTFILES_OS="OpenBSD" ;;
    Darwin)    export DOTFILES_OS="Darwin"  ;;
    SunOS)     export DOTFILES_OS="SunOS"   ;;
    *)         export DOTFILES_OS="Linux"   ;;
esac
[[ $DOTFILES_OS = "Darwin" ]] && {
  case "$(sw_vers -productVersion)" in
    10.7*) export DOTFILES_DISTRO="lion"          ;;
    10.8*) export DOTFILES_DISTRO="mountainlion"  ;;
    10.9*) export DOTFILES_DISTRO="mavericks"     ;;
  esac
}
[[ $DOTFILES_OS = "Linux" ]] && {
  [[ -f "/etc/debian_version" ]] && export DOTFILES_DISTRO="debian"
  [[ -f "/etc/arch-release" ]]   && export DOTFILES_DISTRO="archlinux"
}

# Shell settings ---------------------------------------------------------------
# xdg-user-dirs
[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/user-dirs.dirs" ] && source "${XDG_CONFIG_HOME:-$HOME/.config}/user-dirs.dirs"

export SAVEHIST=1000
export HISTSIZE=1000
export HISTFILESIZE="$HISTSIZE";
export HISTCONTROL=ignoredups;
export HISTIGNORE="ls:cd:cd -:pwd:exit:date:* --help";

# program settings -------------------------------------------------------------
export EDITOR="vim --nofork"
export VISUAL="gvim --nofork"
export PAGER="less"
export LESS="-R"
# Highlight section titles in manual pages
export LESS_TERMCAP_md="${yellow}";
# Don't clear the screen after quitting a manual page
export MANPAGER="less -X";

# apache
[[ -f /etc/apache2/envvars ]] && source /etc/apache2/envvars
has_program "apachectl" && {
  if apachectl -t >/dev/null 2>&1; then
    export APACHE_HTTPD_ROOT="$(apachectl -V | awk '/ -D HTTPD_ROOT/ { print $2 }' | cut -d "=" -f2 | sed 's/\"//g')"
    export APACHE_HTTPD_CONF="$(apachectl -V | awk '/ -D SERVER_CONFIG_FILE/ { print $2 }' | cut -d "=" -f2 | sed 's/\"//g')"
  fi
}

# boot2docker
export DOCKER_HOST=tcp://localhost:4243

# chruby
# overridden in homebrew section if has brew
export CHRUBY_PREFIX="/usr"

# go
# used in shell/paths
export GOPATH="$HOME/go"

# homebrew
has_program "brew" && {
  export HAS_BREW=true
  export BREW_PREFIX="$(brew --prefix)"
  export HOMEBREW_CASK_OPTS="--appdir=/Applications"
  export CHRUBY_PREFIX="$BREW_PREFIX"

  # Ruby use brew openssl if available
  [[ -f $BREW_PREFIX/opt/openssl ]] && export RUBY_CONFIGURE_OPTS="--with-openssl-dir=$BREW_PREFIX/opt/openssl"
}

# git
export GIT_PAGER="$PAGER -eFX"

# node
export NVM_DIR="$HOME/.nvm"
export NODE_PATH="/usr/local/lib/node_modules:$NODE_PATH"
export NPM_PACKAGES="$HOME/.npm-packages"

# Wine
export WINEPREFIX="$HOME/.config/wine/"
export WINEARCH=win32

# z
export _Z_CMD=j

# vim: set ft=sh :
