#!/usr/bin/env bash

FNM_DIR="${XDG_CONFIG_HOME}/fnm"
export FNM_DIR
if [ ! -d "$FNM_DIR" ]; then
  curl https://raw.githubusercontent.com/Schniz/fnm/master/.ci/install.sh |
    bash -s -- \
      --install-dir "$FNM_DIR" \
      --skip-shell
fi
