#!/usr/bin/env bash

if [[ -z "$DOTFILES" ]]; then
  cd -- "$(dirname "$0")/.." || exit 1
  DOTFILES="$PWD"
fi
. "${DOTFILES}/lib/helpers.sh"
. "${DOTFILES}/lib/pretty.bash"

__main() {
  FNM_DIR="${XDG_DATA_HOME}/fnm"
  export FNM_DIR

  __dko_status "Checking for ${FNM_DIR}"
  mkdir -p "$FNM_DIR"
  [ ! -d "$FNM_DIR" ] && {
    __dko_err "Could not create FNM_DIR ${FNM_DIR}"
    return 1
  }

  local script="https://fnm.vercel.app/install"
  __dko_status "Installing ${script} to ${FNM_DIR}"
  curl -fsSL "$script" | bash -s -- \
    --install-dir "$FNM_DIR" \
    --skip-shell \
    || return 1

  __dko_status "Loading"
  eval "$(fnm env)"

  __dko_status "Installing LTS version"
  fnm install --lts

  __dko_status  "To set a version as default, use"
  __dko_status_ "fnm default VERSION"
}
__main
