#!/usr/bin/env bash
#
# Symlink GTK config
#

set -eu

# ============================================================================
# initialize script and dependencies
# ============================================================================

if [[ -z "$DOTFILES" ]]; then
  cd -- "$(dirname "$0")/.." || exit 1
  DOTFILES="$(pwd)"
fi
. "${DOTFILES}/lib/helpers.sh"
. "${DOTFILES}/lib/pretty.bash"

# ==============================================================================
# Main
# ==============================================================================

__dko_status "COPYING ~/.config/gtk-3.0"
if [[ -d "${XDG_CONFIG_HOME}/gtk-3.0" ]]; then
  mv "${XDG_CONFIG_HOME}/gtk-3.0" "${XDG_CONFIG_HOME}/gtk-3.0.old"
fi
cp  -R  "${DOTFILES}/linux/gtk-3.0"  "${XDG_CONFIG_HOME}/"
