#!/usr/bin/env zsh
#

# ============================================================================
# initialize script and dependencies
# ============================================================================

if [[ -z "$DOTFILES" ]]; then
  cd -- "$(dirname "$0")/.." || exit 1
  DOTFILES="$PWD"
fi
. "${DOTFILES}/lib/helpers.sh"
. "${DOTFILES}/lib/pretty.bash"
export PATH="${DOTFILES}/bin:${PATH}"

# ============================================================================

dynamic_profiles_dir="${DOTFILES}/mac/iterm2/DynamicProfiles"
default_dynamic_profile="fura-mono-tomorrow-night-dark"

__dko_status "Set DynamicProfilesPath to ${dynamic_profiles_dir}"
defaults write com.googlecode.iterm2.plist \
  DynamicProfilesPath -string "$dynamic_profiles_dir"

__dko_status "Use ${default_dynamic_profile}"
defaults write com.googlecode.iterm2.plist \
  "Default Bookmark Guid" -string "$default_dynamic_profile"
