#!/usr/bin/env bash
#
# Idempotently set up mac OS
#

# ============================================================================
# initialize script and dependencies
# ============================================================================

if [[ -z "$DOTFILES" ]]; then
  cd -- "$(dirname "$0")/.." || exit 1
  DOTFILES="$(pwd)"
fi
. "${DOTFILES}/lib/helpers.sh"
. "${DOTFILES}/lib/pretty.bash"
export PATH="${DOTFILES}/bin:${PATH}"

# ============================================================================

__dko_require 'brew' || exit 1
__dko_require 'xcrun' || exit 1

"${DOTFILES}/bootstrap/symlink" || exit 1
"${DOTFILES}/bootstrap/cleanup" || exit 1
"${DOTFILES}/bootstrap/terminfo" || exit 1

if [ -f "${HOME}/Library/LaunchAgents/dotfiles.plist" ]; then
  __dko_status "Reloading dotfiles.plist"
  launchctl unload "${HOME}/Library/LaunchAgents/dotfiles.plist"
  launchctl load "${HOME}/Library/LaunchAgents/dotfiles.plist"
else
  __dko_err "dotfiles.plist not symlinked. Run bootstrap/symlink!"
  exit 1
fi

# See https://github.com/postmodern/chruby/issues/196#issuecomment-23826171
if [ -f /etc/zshenv ] && [ ! -f /etc/zprofile ]; then
  __dko_status "Moving /etc/zshenv to /etc/zprofile"
  sudo mv /etc/zshenv /etc/zprofile
else
  __dko_ok "/etc/zshenv not present"
fi

# See https://github.com/pyenv/pyenv/issues/1219#issuecomment-428700763
# Xcode Command Line tools no longer installs needed headers in /include
# https://developer.apple.com/documentation/xcode_release_notes/xcode_10_release_notes
sdk=$(xcrun --show-sdk-path)
if [ ! -d "$sdk" ]; then
  __dko_status "SDK headers not found. Installing"
  sudo installer \
    -pkg "/Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg" \
    -target /
else
  __dko_ok "Found SDK headers"
fi

__dko_status "Brewing"
[ -z "$DKO_BREW_PREFIX" ] && . "${DOTFILES}/shell/os-darwin"
(cd "${DOTFILES}/mac" && TERM=xterm256-color \brew bundle)

__dko_status "Installing fzf shell extensions"
"${DOTFILES}/bin/dot" fzf

# https://rick.cogley.info/post/use-homebrew-zsh-instead-of-the-osx-default/
__dko_status "Setting user shell to brewed zsh using dscl"
if [ -x "${DKO_BREW_PREFIX}/bin/zsh" ]; then
  sudo dscl . -create "/Users/${USER}" UserShell "${DKO_BREW_PREFIX}/bin/zsh"
else
  __dko_warn "Could not update the user's shell to ${DKO_BREW_PREFIX}/bin/zsh"
  __dko_warn_ "Check the brew installation and refer to"
  __dko_warn_ "https://rick.cogley.info/post/use-homebrew-zsh-instead-of-the-osx-default/"
fi

# ============================================================================

__dko_ok "SUCCESS"
__dko_status "Restart your terminal"
