#!/usr/bin/env bash
#
# Set up mac OS
#

# ============================================================================
# initialize script and dependencies
# ============================================================================

if [[ -z "$DOTFILES" ]]; then
  cd -- "$(dirname "$0")/.." || exit 1
  DOTFILES="$(pwd)"
fi
. "${DOTFILES}/lib/helpers.sh"
. "${DOTFILES}/lib/pretty.bash"
export PATH="${DOTFILES}/bin:${PATH}"

# ============================================================================

# See https://github.com/pyenv/pyenv/issues/1219#issuecomment-428700763
# Xcode Command Line tools no longer installs needed headers in /include
# https://developer.apple.com/documentation/xcode_release_notes/xcode_10_release_notes
sudo installer \
  -pkg "/Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg" \
  -target /

# run bootstrap/symlink first!
[ -f "${HOME}/Library/LaunchAgents/dotfiles.plist" ] && \
  launchctl load "${HOME}/Library/LaunchAgents/dotfiles.plist"

# ============================================================================

"${DOTFILES}/bootstrap/symlink-mac"
