#!/usr/bin/env bash

# See https://github.com/pyenv/pyenv/issues/1219#issuecomment-428700763
# Xcode Command Line tools no longer installs needed headers in /include
# https://developer.apple.com/documentation/xcode_release_notes/xcode_10_release_notes
sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /
