#!/usr/bin/env bash
#
# Basic symlinks, safe to run on any system
#

# ============================================================================
# initialize script and dependencies
# ============================================================================

if [[ -z "$DOTFILES" ]]; then
  cd -- "$(dirname "$0")/.." || exit 1
  DOTFILES="$(pwd)"
fi
. "${DOTFILES}/lib/helpers.sh"
. "${DOTFILES}/lib/pretty.bash"
export PATH="${DOTFILES}/bin:${PATH}"

# ============================================================================
# Create paths (slow)
# ============================================================================

mkdir -p -- "${HOME}/.cache"
mkdir -p -- "${HOME}/.config"

# Mirror root in ~/.local
mkdir -p -- "${HOME}/.local/bin"
mkdir -p -- "${HOME}/.local/man/man1"
mkdir -p -- "${HOME}/.local/lib/R/library"
mkdir -p -- "${HOME}/.local/share/tig"

# ============================================================================
# Main
# ============================================================================

__symlink() {
  __dko_status "Symlinking dotfiles"

  # REQUIRED in ~/ -- ag looks for ~/.agignore LAST and includes it.
  # .ignore files are for project local only
  dko-symlink  "shell/dot.profile" \
                ".profile"

  # universal-ctags
  dko-symlink  "universal-ctags/dot.ctags" \
                ".ctags.d/universal.ctags"

  # XDG-compatible
  dko-symlink  "git/dot.gitconfig" \
                ".config/git/config"
  dko-symlink  "git/dot.gitignore" \
                ".config/git/ignore"
  dko-symlink  "markdownlint/dot.markdownlintrc" \
                ".config/markdownlint"
  dko-symlink  "node/default-packages" \
                ".config/nvm/default-packages"
  dko-symlink  "shell/dot.inputrc" \
                ".config/readline/inputrc"
  dko-symlink  "kitty/kitty.conf" \
                ".config/kitty/kitty.conf"

  # (n)vim / intellij ideavim
  dko-symlink  "vim" \
                ".vim"
  dko-symlink  "vim" \
                ".config/nvim"
  dko-symlink  "ideavim/dot.ideavimrc" \
                ".ideavimrc"

  # hyper.app
  dko-symlink  "hyper-app/dot.hyper.js" \
                ".hyper.js"

  # default ~/.tern-config
  dko-symlink  "ternjs/dot.tern-config" \
                ".tern-config"

  case "$OSTYPE" in
    darwin*)
      dko-symlink  "hammerspoon" \
                    ".hammerspoon"
      dko-symlink  "mac/dot.hushlogin" \
                    ".hushlogin"
      dko-symlink  "mac/dotfiles.plist" \
                    "Library/LaunchAgents/dotfiles.plist"
      dko-symlink  "subversion/config" \
                    ".subversion/config"
      dko-symlink  "mac/redshift.conf" \
                    ".config/redshift/redshift.conf"
      ;;
    linux*)
      dko-symlink  "linux/subversion/config" \
                    ".subversion/config"
      ;;
  esac

  # Shell
  dko-symlink  "bash/dot.bashrc" \
                ".bashrc"
  dko-symlink  "bash/dot.bash_profile" \
                ".bash_profile"
  dko-symlink  "zsh/dot.zshenv" \
                ".zshenv"

  __dko_status "Done! [symlink.sh]"
}

__symlink
