#!/usr/bin/env bash
#
# Basic symlinks, safe to run on any system
#

# ============================================================================
# initialize script and dependencies
# ============================================================================

if [[ -z "$DOTFILES" ]]; then
  cd -- "$(dirname "$0")/.." || exit 1
  DOTFILES="$PWD"
fi
. "${DOTFILES}/lib/helpers.sh"
. "${DOTFILES}/lib/pretty.bash"
export PATH="${DOTFILES}/bin:${PATH}"

# ============================================================================
# Create paths (slow)
# ============================================================================

mkdir -p -- "${HOME}/.cache"
mkdir -p -- "${HOME}/.config"

# Mirror root in ~/.local
# pipx uses this bin dir
mkdir -p -- "${HOME}/.local/bin"
mkdir -p -- "${HOME}/.local/man/man1"
mkdir -p -- "${HOME}/.local/lib/R/library"
mkdir -p -- "${HOME}/.local/share/tig"

# ============================================================================
# Main
# ============================================================================

__symlink() {
  __dko_status "Symlinking dotfiles"

  # REQUIRED in ~/ -- ag looks for ~/.agignore LAST and includes it.
  # .ignore files are for project local only
  dko-symlink "shell/dot.profile" \
    ".profile"

  # XDG-compatible, not linux specific
  dko-symlink "bat/config" \
    ".config/bat/config"
  dko-symlink "git/dot.gitconfig" \
    ".config/git/config"
  dko-symlink "git/dot.gitignore" \
    ".config/git/ignore"
  dko-symlink "markdownlint/dot.markdownlintrc" \
    ".config/markdownlint/config"
  dko-symlink "shell/dot.inputrc" \
    ".config/readline/inputrc"
  # whole wezterm directory
  dko-symlink "wezterm" \
    ".config/wezterm"
  dko-symlink "yamlfmt" \
    ".config/yamlfmt"

  # (n)vim / intellij ideavim
  dko-symlink "vim" \
    ".vim"
  dko-symlink "nvim" \
    ".config/nvim"
  dko-symlink "ideavim/dot.ideavimrc" \
    ".config/ideavim/ideavimrc"

  case "$OSTYPE" in
  *arwin*)
    dko-symlink "mac/hammerspoon" \
      ".hammerspoon"
    dko-symlink "mac/dot.hushlogin" \
      ".hushlogin"
    dko-symlink "mac/dot.mackup.cfg" \
      ".mackup.cfg"
    ;;
  esac

  # Shell
  dko-symlink "bash/dot.bashrc" \
    ".bashrc"
  dko-symlink "bash/dot.bash_profile" \
    ".bash_profile"
  dko-symlink "zsh/dot.zshenv" \
    ".zshenv"

  __dko_status "Done! [symlink.sh]"
}

__symlink
