#!/usr/bin/env bash
#
# Set up mac OS
#

# ============================================================================
# initialize script and dependencies
# ============================================================================

if [[ -z "$DOTFILES" ]]; then
  cd -- "$(dirname "$0")/.." || exit 1
  DOTFILES="$(pwd)"
fi
. "${DOTFILES}/lib/helpers.sh"
. "${DOTFILES}/lib/pretty.bash"
export PATH="${DOTFILES}/bin:${PATH}"

# ============================================================================

dko-symlink "mac/LaunchAgents/dotfiles.plist" \
            "Library/LaunchAgents/dotfiles.plist"
launchctl load "${HOME}/Library/LaunchAgents/dotfiles.plist"
