#!/usr/bin/env bash
#
# Symlink termite config
#

set -eu

# ============================================================================
# initialize script and dependencies
# ============================================================================

cd -- "$(dirname "$0")/.." || exit 1
readonly dotfiles_path="$(pwd)"
. "${DOTFILES}/lib/helpers.sh"
. "${DOTFILES}/lib/pretty.bash"

# ==============================================================================
# Main
# ==============================================================================

__dko_status "Symlinking termite config"
__dko_symlink "termite/config" ".config/termite/config"

__dko_status "Installing terminfo"
tic -x -- "${dotfiles_path}/termite/termite.terminfo"
