#!/usr/bin/env bash
#
# Symlink termite config
#

set -eu

# ============================================================================
# initialize script and dependencies
# ============================================================================

if [[ -z "$DOTFILES" ]]; then
  cd -- "$(dirname "$0")/.." || exit 1
  DOTFILES="$(pwd)"
fi
. "${DOTFILES}/lib/helpers.sh"
. "${DOTFILES}/lib/pretty.bash"

# ==============================================================================
# Main
# ==============================================================================

__dko_status "Symlinking termite config"
dko-symlink "linux/termite/config" ".config/termite/config"

__dko_status "Installing terminfo"
tic -x -- "${DOTFILES}/linux/termite/termite.terminfo"
