#!/usr/bin/env bash
#
# Copy compiled terminfo files
#

# errors are okay.
#set -eu

# ============================================================================
# initialize script and dependencies
# ============================================================================

cd -- "$(dirname "$0")/.." || exit 1
readonly dotfiles_path="$(pwd)"
. "${DOTFILES}/lib/pretty.bash"

# ==============================================================================
# Main
# ==============================================================================

__dko_status "Copying terminfo files"

TERMINFO="${TERMINFO:-${XDG_DATA_HOME}/terminfo}"

# RXVT
mkdir -p -- "${TERMINFO}/r"
[[ -d "${dotfiles_path}/terminfo/r" ]] && \
  cp -R -- "${dotfiles_path}/terminfo/r/*" "${TERMINFO}/r/"

# Install all uncompiled terminfo files, e.g.
# - xterm-256color-italic for iterm2
# - tmux-256color for tmux
find "${dotfiles_path}/terminfo/" -name '*.terminfo' -exec tic -x {} \;
