#!/usr/bin/env bash
#
# Symlink X11 settings
#

# ============================================================================
# initialize script and dependencies
# ============================================================================

cd -- "$(dirname "$0")/.." || exit 1
readonly dotfiles_path="$(pwd)"
. "${DOTFILES}/lib/helpers.sh"
. "${DOTFILES}/lib/pretty.bash"

# ==============================================================================
# Main
# ==============================================================================

__dko_status "Symlinking X11 dotfiles"
# this probably isn't sourced by your session
__dko_symlink "linux/.xinitrc"       ".xinitrc"
__dko_symlink "linux/.xbindkeysrc"   ".xbindkeysrc"
__dko_symlink "linux/.xprofile"      ".xprofile"
