#!/usr/bin/env bash
#
# Create XDG dirs
#

set -e

if [[ -z "$DOTFILES" ]]; then
  cd -- "$(dirname "$0")/.." || exit 1
  DOTFILES="$PWD"
fi
. "${DOTFILES}/lib/helpers.sh"
. "${DOTFILES}/lib/pretty.bash"

[[ $DKO_SOURCE == *"shell/vars"* ]] || {
  echo "Must source shell/vars.sh first"
  exit 1
}

mkdir -p -- "$XDG_STATE_HOME"
mkdir -p -- "$BZR_PLUGIN_PATH"
mkdir -p -- "$BZR_HOME"
mkdir -p -- "$COMPOSER_CACHE_DIR"
[[ "$FONTCONFIG_PATH" != "" ]] && mkdir -p -- "$FONTCONFIG_PATH"
mkdir -p -- "$GNUPGHOME"
mkdir -p -- "$(dirname $NPM_CONFIG_USERCONFIG)"
