#!/usr/bin/env bash

# =============================================================================
# Require DOTFILES
# =============================================================================

if [[ -z "$DOTFILES" ]]; then
  cd -- "$(dirname "$0")/.." || exit 1
  DOTFILES="$PWD"
fi
. "${DOTFILES}/lib/helpers.sh"
. "${DOTFILES}/lib/pretty.bash"

# =============================================================================
# Main
# =============================================================================

__install() {
  __dko_has 'luarocks' || {
    __dko_err "Please install luarocks"
    exit 1
  }

  local cmd="luarocks"
  [[ -n "$DKO_LUA_DIR" ]] && {
    cmd="luarocks --lua-dir=\"$DKO_LUA_DIR\""
    __dko_status "Using lua in ${DKO_LUA_DIR}"
  }

  # loop through default-gems file and install each one
  __dko_status "Installing lua packages"
  while read -r pkg; do
    eval "$cmd install --local $pkg"
  done <"${DOTFILES}/lua/packages"
}

__install
