# ==========================================================================
# taps
# ==========================================================================

# skhd.zig hotkey daemon (used to free up cmd-ctrl-d from macOS Dictionary)
tap "jackielii/tap"

# ==========================================================================
# brew'd apps I use on ALL macs
# ==========================================================================

# hotkey daemon; my skhd config forwards cmd-ctrl-d to hammerspoon
brew "jackielii/tap/skhd-zig"

brew "git"

# my hammerspoon config uses this
brew "switchaudio-osx"

brew "tree"

# ==========================================================================
# casks
# ==========================================================================

cask "bettertouchtool"
cask "firefox"
cask "google-chrome"
cask "hammerspoon"
cask "meetingbar"
cask "wezterm@nightly"
