#!/usr/bin/env bash

set -e

# =============================================================================
# Require DOTFILES
# =============================================================================

if [ -z "$DOTFILES" ]; then
  echo ".dotfiles repo is not set up"
  exit 1
fi
source "${DOTFILES}/shell/helpers.bash"

# ============================================================================

# Clean room
# reset TERM since we use custom one in iTerm
TERM=xterm-256color

# ============================================================================
# taps
# ============================================================================

# brew services launchctl manager -- no formulae
brew tap homebrew/services

# ============================================================================
# Meta
# ============================================================================

brew update

# brew cask completion
brew install brew-cask-completion

# ============================================================================
# compilers, tools, and libs
# ============================================================================

brew install automake cmake
brew install coreutils findutils moreutils
brew install libtool
brew install pkg-config

# ============================================================================
# general
# ============================================================================

brew install aspell
brew install archey neofetch
brew install asciinema
dko::status "asciinema auth to link computer to account"
brew install awscli
brew install catimg

# ============================================================================
# vim
# ============================================================================

brew install neovim

# ============================================================================
# filesystem
# ============================================================================

brew install ack
brew install fzf
brew install tree
brew install ripgrep

# prefer ripgrep
# brew install the_silver_searcher

# ============================================================================
# operations
# ============================================================================

# OpenSSL for some programs, but prefer libressl where possible
brew install openssl

# Too annoying to re-setup ssh-agent since the ssh-add does not have keychain
# access -- disabled:
# ----------------------------------------------------------------------------
# Install a newer version of OpenSSH
# that isn't susceptible to http://www.openssh.com/txt/release-7.1p2
#brew install homebrew/dupes/ssh --with-libressl

# better curl
brew install curl --with-libressl
brew link --force curl

brew install htop --with-ncurses

brew install multitail
brew install nmap
brew install ssh-copy-id
brew install wget
brew install wifi-password

# Use the `gpgtools` cask instead (it also provides cli `gpg` and
# `gpg-agent`). It provides a nicer gui prefpane and automatic integration
# without having to configure all this stuff.
#brew install gnupg2
#brew install gpg-agent pinentry-mac

# ============================================================================
# pretty print and processor
# ============================================================================

brew install ccat
brew install diff-so-fancy icdiff
brew install jsonpp jq

# ============================================================================
# programming
# ============================================================================

brew install php71
brew install homebrew/homebrew-php/composer

brew install --HEAD universal-ctags/universal-ctags/universal-ctags

brew install cloc

# used by fzf grepper preview
brew install highlight

# ios dev
brew install carthage

brew install lua
brew install mono
brew install tidy-html5

brew install yarn

# ----------------------------------------------------------------------------
# java
# ----------------------------------------------------------------------------

brew install gradle --with-all
brew install maven

# ----------------------------------------------------------------------------
# git
# ----------------------------------------------------------------------------

brew install git --without-completions
brew install git-extras
brew install hub tig

# ============================================================================
# shells
# ============================================================================

# bash 4 shell
brew install bash bash-completion@2
brew install bats shellcheck shfmt
brew install tmux
brew install zsh

# ============================================================================
# docker
# ============================================================================

# docker itself is installed from cask
brew install docker-completion

# ============================================================================
# ethereum client
# ============================================================================

brew install ethereum/ethereum/ethereum

# ============================================================================
# OS
# ============================================================================

# Only if system has no camera
dko::status   "Redshift was not installed; only needed if there is no camera."
dko::status_  "brew install redshift"

brew install mas
