#!/usr/bin/env bash

set -e

brew update

# ==============================================================================
# bettertouchtool
# ==============================================================================

brew cask install bettertouchtool
echo "License in SpiderOak Hive"

# ==============================================================================

brew cask install balenaetcher
brew cask install betwixt
brew cask install bitwarden
brew cask install brave

brew cask install cloudapp

brew cask install dash

# full socks5+DHT+blocklist support
brew cask install deluge

brew cask install discord
brew cask install disk-inventory-x
brew cask install docker
brew cask install dropbox
brew cask install firefox
brew cask install gimp
brew cask install gitter
brew cask install google-chrome
brew cask install gpg-suite-no-mail
brew cask install hammerspoon

# inkscape requires xquartz
brew cask install xquartz
brew cask install inkscape

brew cask install iina
brew cask install iterm2
brew cask install itsycal

#brew cask install java
#brew cask install java8

brew cask install joplin

# ==============================================================================
# Kaleidoscope
# ==============================================================================

brew cask install kaleidoscope
echo "License in SpiderOak Hive"

# ==============================================================================
# Marked
# ==============================================================================

brew cask install marked
echo "License in SpiderOak Hive"

# ==============================================================================

brew cask install ngrok
brew cask install robo-3t
brew cask install skype
brew cask install slack
brew cask install spideroakone
brew cask install spotify
brew cask install synology-drive
brew cask install synologyassistant
brew cask install telegram
# brew cask install switchresx
brew cask install the-unarchiver

# ==============================================================================
# Transmit
# ==============================================================================

brew cask install transmit
echo "License in email"
echo "Favorites in SpiderOak sync"

# ============================================================================

brew cask install tunnelblick
echo "Set up vpn"

# ============================================================================
# Virtualization
# ============================================================================

brew cask install vagrant
brew cask install virtualbox virtualbox-extension-pack

# ============================================================================

brew cask install vnc-viewer
