#!/usr/bin/env bash

# =============================================================================
# Require DOTFILES
# =============================================================================

if [[ -z "$DOTFILES" ]]; then
  echo ".dotfiles repo is not set up"
  exit 1
fi
. "${DOTFILES}/lib/pretty.bash"

# ============================================================================

__maxfiles() {
  local limit="${1:-65536}"

  __dko_status "Settings kern.maxfiles[perproc] and ulimit to ${limit}"

  echo kern.maxfiles="$limit" | sudo tee -a /etc/sysctl.conf
  echo kern.maxfilesperproc="$limit" | sudo tee -a /etc/sysctl.conf
  sudo sysctl -w kern.maxfiles="$limit"
  sudo sysctl -w kern.maxfilesperproc="$limit"
  ulimit -n "$limit"

  __dko_status "Please reboot for changes to take effect"
}

__maxfiles "$@"
