[env]
# API keys (must be set in environment or mise.local.toml)
# or define all of these in a file of ~/.config/mise/conf.d/*.toml
EMAIL = { required = true }
GIT_AUTHOR_NAME = { required = true }
GIT_COMMITTER_NAME = { required = true }
NPM_CONFIG_INIT_AUTHOR_NAME = { required = true }
GIT_AUTHOR_EMAIL = { required = true }
GIT_COMMITTER_EMAIL = { required = true }

[settings]
gpg_verify = false
experimental = false

[settings.github]
use_git_credentials = true

# tombi: format.rules.table-keys-order = "ascending"
[tools]
act = "latest"
actionlint = "latest"
bat = "latest"
biome = "latest"
"cargo:selene" = { version = "latest", depends = ["rust"] }
"cargo:shuck-cli" = { version = "latest", depends = ["rust"] }
delta = "latest"
fd = "latest"
fzf = "latest"
github-cli = "latest"
"github:skanehira/version-lsp" = "latest"
go = "1.27.0"
"go:github.com/mattn/efm-langserver" = { version = "latest", depends = ["go"] }
"go:golang.org/x/tools/gopls" = { version = "latest", depends = ["go"] }
hadolint = "latest"
"http:git-relevant" = { version = "0.0.0", url = "https://raw.githubusercontent.com/davidosomething/git-relevant/refs/heads/master/git-relevant" }
"http:git-take" = { version = "0.0.0", url = "https://raw.githubusercontent.com/davidosomething/git-take/refs/heads/master/git-take" }
jq = "latest"
lua-language-server = "latest"
marksman = "latest"
neovim = "latest"
node = "latest"
"npm:@actions/languageserver" = { version = "latest" }
"npm:@microsoft/compose-language-service" = { version = "latest" }
"npm:@tailwindcss/language-server" = { version = "latest" }
"npm:@vtsls/language-server" = { version = "latest" }
"npm:dockerfile-language-server-nodejs" = { version = "latest" }
"npm:markdownlint-cli" = { version = "latest" }
"npm:npmrc" = { version = "latest" }
"npm:vscode-langservers-extracted" = { version = "latest" }
"npm:yaml-language-server" = { version = "latest" }
"pipx:basedpyright" = { version = "latest", depends = ["python"] }
"pipx:isort" = { version = "latest", depends = ["python"] }
"pipx:jedi-language-server" = { version = "latest", depends = ["python"] }
prettier = { version = "latest" }
python = "latest"
ripgrep = { version = "latest", postinstall = "[ -n \"${XDG_DATA_HOME}\" ] && mkdir -p ${XDG_DATA_HOME}/zsh/site-functions && rg --generate complete-zsh > ${XDG_DATA_HOME}/zsh/site-functions/_rg || true" }
ruff = "latest"
rust = "latest"
rust-analyzer = { version = "latest", depends = ["rust"] }
shellcheck = "latest"
stylua = "latest"
terraform-ls = "latest"
tombi = "latest"
tree-sitter = "latest"
usage = "latest"
uv = "latest"
yamlfmt = "latest"
yamllint = "latest"
zoxide = "latest"
