[settings]
gpg_verify = false
experimental = false

# tombi: format.rules.table-keys-order = "ascending"
[tools]
"aqua:neovim/neovim" = "latest"
biome = "latest"
# @TODO fix completions for bat
"cargo:selene" = "latest"
# @TODO fix completions for fd
delta = "latest"
fd = "latest"
fzf = "latest"
# @TODO fix completions for cli
github-cli = "latest"
"github:skanehira/version-lsp" = "latest"
go = "1.26.1"
"go:github.com/mattn/efm-langserver" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
hadolint = "latest"
"http:git-relevant" = { version = "0.0.0", url = "https://raw.githubusercontent.com/davidosomething/git-relevant/refs/heads/master/git-relevant" }
"http:git-take" = { version = "0.0.0", url = "https://raw.githubusercontent.com/davidosomething/git-take/refs/heads/master/git-take" }
# @TODO fix completions for jq
jq = "latest"
lua-language-server = "latest"
marksman = "latest"
node = "latest"
"npm:@mdx-js/language-server" = "latest"
"npm:@microsoft/compose-language-service" = "latest"
"npm:@tailwindcss/language-server" = "latest"
"npm:@vtsls/language-server" = "latest"
"npm:dockerfile-language-server-nodejs" = "latest"
"npm:gh-actions-language-server" = "latest"
"npm:markdownlint-cli" = "latest"
"npm:npmrc" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:yaml-language-server" = "latest"
"pipx:basedpyright" = "latest"
"pipx:isort" = "latest"
"pipx:jedi-language-server" = "latest"
prettier = "latest"
python = "latest"
ripgrep = { version = "latest", postinstall = "[ -n \"${XDG_DATA_HOME}\" ] && mkdir -p ${XDG_DATA_HOME}/zsh/site-functions && rg --generate complete-zsh > ${XDG_DATA_HOME}/zsh/site-functions/_rg || true" }
ruff = "latest"
rust = "latest"
rust-analyzer = "latest"
shellcheck = "latest"
shfmt = "latest"
stylua = "latest"
terraform-ls = "latest"
tombi = "latest"
tree-sitter = "latest"
usage = "latest"
uv = "latest"
vault = "latest"
yamlfmt = "latest"
yamllint = "latest"
