#!/usr/bin/env bash

set -e

# =============================================================================
# Require DOTFILES
# =============================================================================

if [ -z "$DOTFILES" ]; then
  echo ".dotfiles repo is not set up"
  exit 1
fi
. "${DOTFILES}/lib/helpers.sh"
. "${DOTFILES}/lib/pretty.bash"
. "${DOTFILES}/shell/node.sh"

fnm use default
fnm list
node --version
npm --version

# =============================================================================
# Main
# =============================================================================

__install() {
  __dko_status "Installing global node packages"
  while read -r package; do
    "${DOTFILES}/bin/dko-header" "$package"
    # npm ls --global --parseable --depth=0 "$package" ||
    npm install --global --production "$package"
    echo
    echo
  done < "${DOTFILES}/node/default-packages"
}
__dko_has npm && __install "$@"
