#!/usr/bin/env bash

set -e

# =============================================================================
# Require DOTFILES
# =============================================================================

if [ -z "$DOTFILES" ]; then
  echo ".dotfiles repo is not set up"
  exit 1
fi
. "${DOTFILES}/lib/helpers.sh"
. "${DOTFILES}/lib/pretty.bash"

# =============================================================================
# Main
# =============================================================================

# @TODO check for nvm node
__install() {
  __dko_status "Installing latest npm"
  npm install --global --production npm@latest

  __dko_status "Installing Yeoman"
  npm install --global --production yo

  __dko_status "Checking npm environment using yo doctor"
  yo doctor || exit 1

  __dko_status "Installing global node packages"
  # peer dep packages
  npm install --global --production eslint

  # loop through packages.txt file and install each one
  while read -r package; do
    if [ "$package" != "yo" ] \
      && [ "$package" != "eslint" ]; then
      # npm ls --global --parseable --depth=0 "$package" ||
      npm install --global --production "$package"
    fi
  done < "${DOTFILES}/node/default-packages"
}

__install "$@"
