#!/usr/bin/env bash

# =============================================================================
# Require DOTFILES
# =============================================================================

if [ -z "$DOTFILES" ]; then
  echo ".dotfiles repo is not set up"
  exit 1
fi
. "${DOTFILES}/lib/helpers.sh"
. "${DOTFILES}/lib/pretty.bash"
. "${DOTFILES}/shell/node.sh"

fnm use default

# =============================================================================
# Main
# =============================================================================

# @TODO check for nvm node
__install() {
  __dko_status "Installing latest npm"
  npm install --global --production npm@latest

  __dko_status "Installing global node packages"
  while read -r package; do
    # npm ls --global --parseable --depth=0 "$package" ||
    npm install --global --production "$package"
  done < "${DOTFILES}/node/default-packages"
}

__dko_has npm && __install "$@"
