#!/usr/bin/env bash

set -e

if [ -z "$DOTFILES" ]; then
  echo ".dotfiles repo is not set up"
  exit 1
fi
. "${DOTFILES}/lib/helpers.sh"
. "${DOTFILES}/lib/pretty.bash"

# =============================================================================
# Main
# =============================================================================

__usage() {
  echo "Usage: $0 sourcedir/scriptname.sh"
}

__add() {
  [[ -z $1 ]] && {
    __usage
    exit 1
  }

  [[ ! -f $1 ]] &&  {
    __dko_err "Could not find ${1}"
    exit 1
  }

  local _basename
  _basename="$(basename "$1")"
  local _fullsource
  _fullsource="$(realpath "$1")"
  ln -sf -- "${_fullsource}" "enabled/${_basename}" \
    && __dko_ok "enabled/${_basename} linked to ${_fullsource}"
}

__add "$@"
