#!/usr/bin/env bash

set -e

# =============================================================================
# Require DOTFILES
# =============================================================================

if [ -z "$DOTFILES" ]; then
  echo ".dotfiles repo is not set up"
  exit 1
fi
. "${DOTFILES}/lib/pretty.bash"

# =============================================================================
# Main
# =============================================================================

__install() {
  # Make sure not using system python and pip
  if pip --version | grep -q /usr/lib; then
    __dko_err  "System pip detected, not running. Use a userspace python's pip."
    exit 1
  fi

  # Make sure has pyenv
  if ! __dko_has "pyenv"; then
    __dko_err  "pyenv is not installed. Install it and set up a global pyenv."
    exit 1
  fi

  if pyenv version | grep system >/dev/null; then
    __dko_err  "Using system pyenv. Use real pyenv instead."
    exit 1
  fi

  __dko_status "Updating global pip"
  pip install --upgrade pip

  __dko_status "Updating global pip requirements"
  pip install --upgrade --requirement "${DOTFILES}/python/requirements.txt"
}

__install "$@"
