#!/usr/bin/env bash

set -e

# =============================================================================
# Require DOTFILES
# =============================================================================

if [[ -z "$DOTFILES" ]]; then
  cd -- "$(dirname "$0")/.." || exit 1
  DOTFILES="$PWD"
fi
. "${DOTFILES}/lib/helpers.sh"
. "${DOTFILES}/lib/pretty.bash"
. "${DOTFILES}/shell/python.sh"
export PATH="${DOTFILES}/bin:${PATH}"

# =============================================================================
# Main
# =============================================================================

__install() {
  # Make sure not using system python and pip
  if python -m pip --version | grep -q /usr/lib; then
    __dko_err  "System pip detected, not running. Use a userspace python's pip."
    exit 1
  fi

  # Make sure has pyenv
  if ! __dko_has "pyenv"; then
    __dko_err  "pyenv is not installed. Install it and set up a global pyenv."
    exit 1
  fi

  if pyenv version | grep -q system; then
    __dko_err  "Using system pyenv. Use real pyenv instead."
    exit 1
  fi

  __dko_status "Updating global pip"
  python -m pip install --upgrade pip

  __dko_status "Updating global pip requirements"
  python -m pip install --upgrade --requirement "${DOTFILES}/python/requirements.txt"
}
__install "$@"
