install ack
install autojump
install php54
install php54-mcrypt
install curl-ca-bundle
install ctags-exuberant
install dnsmasq
install git
install git-extras
install irssi
install jsonpp
install macvim --override-system-vim
install mysql
install nmap
install node
install openssl
install rbenv
install rbenv-gem-rehash
install rbenv-default-gems
install ruby-build
install rsync
install ssh-copy-id
install the_silver_searcher
install tree
install zsh
install zsh-completions

# tap homebrew/dupes
# install apple-gcc42

tap josegonzalez/homebrew-php
install composer
install php55
install php55-mcrypt
install phpmyadmin

tap homebrew/completions
install vagrant-completion

tap phinze/homebrew-cask
install brew-cask
