# standard homebrew formula
install ack
install autojump
install php54
install php54-mcrypt
install cmake
install curl
install curl-ca-bundle
install ctags
install direnv
install dnsmasq
install git
install git-extras
install hub
install irssi
install jsonpp
install macvim --override-system-vim
install mysql
install nmap
install node
install openssl
install rbenv
install rbenv-gem-rehash
install rbenv-default-gems
install ruby-build
install rsync
install ssh-copy-id
install the_silver_searcher
install tree
install wget
install wp-cli
install zsh
install zsh-completions

# tap homebrew/dupes
# install apple-gcc42

tap josegonzalez/homebrew-php
install composer
install php55
install php55-mcrypt
install phpmyadmin

tap homebrew/completions
install vagrant-completion

tap phinze/homebrew-cask
install brew-cask
cask install google-chrome
cask install caffeine
cask install transmit
cask install vagrant
cask install virtualbox
