# standard homebrew formula
install ack
install autojump
install php54
install php54-mcrypt
install cmake
install curl
install curl-ca-bundle
install ctags
install direnv
install dnsmasq
install git
install git-extras
install hub
install irssi
install jsonpp
install macvim --override-system-vim
install mysql
install nmap
install node
install openssl
install rbenv
install rbenv-gem-rehash
install rbenv-default-gems
install ruby-build
install rsync
install ssh-copy-id
install the_silver_searcher
install tree
install wget
install wp-cli
install zsh
install zsh-completions

# tap homebrew/dupes
# install apple-gcc42

tap josegonzalez/homebrew-php
install composer
install php55
install php55-mcrypt
install phpmyadmin

tap homebrew/completions
install vagrant-completion

tap phinze/homebrew-cask
install brew-cask
cask install adium
cask install alfred
cask install android-file-transfer
cask install bettertouchtool
cask install bowtie
cask install caffeine
cask install cord
cask install dash
cask install dropbox
cask install firefox
cask install gitifier
cask install google-chrome
cask install google-drive
cask install iterm2
cask install jing
cask install join-me
cask install kaleidoscope
cask install keyremap4macbook
cask install lastfm
cask install lastpass-universal
cask install noejectdelay
cask install nosleep
cask install nvalt
cask install skype
cask install toggldesktop
cask install transmit
cask install vagrant
cask install virtualbox
cask install vlc
cask install xquartz

# quicklook
cask install betterzipql
cask install qlcolorcode
cask install qlimagesize
cask install qlmarkdown
cask install qlstephen

