#!/usr/bin/env bash
#
# Tap and install caskroom apps
#

set -eu

brew tap caskroom/cask
brew tap caskroom/versions

brew update

# ==============================================================================
# Alfred
# ==============================================================================

brew cask install alfred
echo "License in SpiderOak Hive"
echo "Workflows in SpiderOak Hive"

# ==============================================================================
# bettertouchtool
# ==============================================================================

brew cask install bettertouchtool
echo "License in SpiderOak Hive"

# ==============================================================================

brew cask install bitbar
echo "Sync in SpiderOak Hive"

brew cask install discord
brew cask install docker
brew cask install dropbox
brew cask install gitter
brew cask install google-chrome-beta
brew cask install gpgtools
brew cask install iterm2-beta
brew cask install java
brew cask install jing
brew cask install joinme

# ==============================================================================
# Kaleidoscope
# ==============================================================================

brew cask install kaleidoscope
echo "License in SpiderOak Hive"

# ==============================================================================

brew cask install karabiner-elements
brew cask install keybase

# ==============================================================================
# Marked
# ==============================================================================

brew cask install marked
echo "License in SpiderOak Hive"

# ==============================================================================

brew cask install ngrok
brew cask install skype
brew cask install slack
brew cask install spideroakone
brew cask install spotify spotifree
brew cask install the-unarchiver
brew cask install transmission

# ==============================================================================
# Transmit
# ==============================================================================

brew cask install transmit
echo "License in email"
echo "Favorites in SpiderOak sync"

# ============================================================================

brew cask install tunnelblick
echo "Set up AirVPN ovpns"

# ============================================================================
# Virtualization
# ============================================================================

brew cask install vagrant vagrant-manager
brew cask install virtualbox virtualbox-extension-pack

# ============================================================================

brew cask install vlc
brew cask install vnc-viewer

