####
# .dotfiles/bash/bashrc
# read on all shells and subshells

##
# bash options
set -o notify
shopt -s checkwinsize # useful for tmux
shopt -s histappend
shopt -s nocaseglob
shopt -s extglob
shopt -s cdspell
shopt -s cdable_vars

source $HOME/.dotfiles/bash/vars
source $BASH_DOTFILES/rbenv
source $BASH_DOTFILES/paths
source $BASH_DOTFILES/completions
source $BASH_DOTFILES/prompt
source $BASH_DOTFILES/aliases # sources os specifics too
source $BASH_DOTFILES/functions # sources os specifics too

##
# os specific
case "$OSTYPE" in
  darwin*)  [ -f "$BASH_DOTFILES/bashrc-osx" ] && source "$BASH_DOTFILES/bashrc-osx"
            ;;
  linux*)   [ -f "$BASH_DOTFILES/bashrc-linux" ] && source "$BASH_DOTFILES/bashrc-linux"
            ;;
esac
