---
name: release

on:
  workflow_run:
    workflows: [test]
    types:
      - completed

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0

      - name: Merge dev -> master
        uses: devmasx/merge-branch@854d3ac71ed1e9deb668e0074781b81fdd6e771f  # 1.4.0
        with:
          type: now
          from_branch: dev
          target_branch: master
          github_token: ${{ github.token }}
